# Generated by Django 5.0.2 on 2024-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectividad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
