# Generated by Django 5.0.2 on 2024-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selectividad', '0002_delete_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField()),
                ('universidad', models.CharField(max_length=100)),
                ('peticion', models.IntegerField()),
                ('grado', models.CharField(max_length=300)),
                ('centro', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=300)),
                ('general', models.FloatField()),
            ],
        ),
    ]
